[package]
name = "krit-cli"
description = "Command-line interface for the Krit programming language"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "krit"
path = "src/main.rs"

[dependencies]
krit.workspace = true
krit-package.workspace = true
krit-runtime.workspace = true
krit-wasm.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
tiny_http.workspace = true

[lints]
workspace = true
