[package]
name = "krit-cli"
description = "Command-line interface for the Krit programming language"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "krit"
path = "src/main.rs"

[dependencies]
krit.workspace = true
krit-package.workspace = true

[lints]
workspace = true
