[workspace]
members = [
    "crates/krit",
    "crates/krit-cli",
    "crates/krit-package",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.94"
authors = ["Akshay Bhardwaj"]
license = "Apache-2.0"
repository = "https://github.com/akshay-bhardwaj/Krit"

[workspace.dependencies]
krit = { path = "crates/krit" }
krit-package = { path = "crates/krit-package" }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = "symbols"
