package krit:runtime@0.2.0;

interface stdout {
    write-int: func(value: s64, newline: bool);
    write-bool: func(value: bool, newline: bool);
    write-unit: func(newline: bool);
}

interface webhook {
    record header {
        name: string,
        value: string,
    }

    record request {
        method: string,
        path: string,
        query: string,
        headers: list<header>,
        body: string,
    }

    record response {
        status: s64,
        headers: list<header>,
        body: string,
    }

    handle: func(request: request) -> response;
}

interface config {
    get-string: func(key: string) -> result<string, string>;
}

interface secrets {
    resource secret;

    acquire: func(name: string) -> result<secret, string>;
}

interface http {
    use secrets.{secret};

    record header {
        name: string,
        value: string,
    }

    record request {
        method: string,
        path: string,
        query: string,
        headers: list<header>,
        body: string,
    }

    record response {
        status: s64,
        headers: list<header>,
        body: string,
    }

    send: func(
        origin: string,
        request: request,
        bearer: option<borrow<secret>>,
    ) -> result<response, string>;
}

interface http-anonymous {
    record header {
        name: string,
        value: string,
    }

    record request {
        method: string,
        path: string,
        query: string,
        headers: list<header>,
        body: string,
    }

    record response {
        status: s64,
        headers: list<header>,
        body: string,
    }

    send: func(origin: string, request: request) -> result<response, string>;
}

world pure-program {
    export run: func();
}

world program {
    import stdout;
    export run: func();
}

world webhook-program {
    export webhook;
}

world webhook-stdout-program {
    import stdout;
    export webhook;
}

world webhook-config-program {
    import config;
    export webhook;
}

world webhook-secrets-program {
    import secrets;
    export webhook;
}

world webhook-http-program {
    import http-anonymous;
    export webhook;
}

world webhook-stdout-config-program {
    import stdout;
    import config;
    export webhook;
}

world webhook-stdout-secrets-program {
    import stdout;
    import secrets;
    export webhook;
}

world webhook-stdout-http-program {
    import stdout;
    import http-anonymous;
    export webhook;
}

world webhook-config-secrets-program {
    import config;
    import secrets;
    export webhook;
}

world webhook-config-http-program {
    import config;
    import http-anonymous;
    export webhook;
}

world webhook-secrets-http-program {
    import secrets;
    import http;
    export webhook;
}

world webhook-stdout-config-secrets-program {
    import stdout;
    import config;
    import secrets;
    export webhook;
}

world webhook-stdout-config-http-program {
    import stdout;
    import config;
    import http-anonymous;
    export webhook;
}

world webhook-stdout-secrets-http-program {
    import stdout;
    import secrets;
    import http;
    export webhook;
}

world webhook-config-secrets-http-program {
    import config;
    import secrets;
    import http;
    export webhook;
}

world webhook-stdout-config-secrets-http-program {
    import stdout;
    import config;
    import secrets;
    import http;
    export webhook;
}

interface ai {
    invoke: func(adapter: string, input: string) -> result<string, string>;
}

interface logging {
    record field {
        name: string,
        value: string,
    }

    info: func(event: string, fields: list<field>) -> result<_, string>;
    error: func(event: string, fields: list<field>) -> result<_, string>;
}

interface state {
    record header {
        name: string,
        value: string,
    }

    record request {
        method: string,
        path: string,
        query: string,
        headers: list<header>,
        body: string,
    }

    record response {
        status: s64,
        headers: list<header>,
        body: string,
    }

    get: func(store: string, key: string) -> result<option<string>, string>;
    put: func(store: string, key: string, value: string) -> result<_, string>;
    delete: func(store: string, key: string) -> result<_, string>;
    checkpoint-get: func(store: string, name: string) -> result<option<string>, string>;
    checkpoint-put: func(store: string, name: string, value: string) -> result<_, string>;
    replay-http: func(
        store: string,
        operation: string,
        origin: string,
        request: request,
    ) -> result<response, string>;
    replay-ai: func(
        store: string,
        operation: string,
        adapter: string,
        input: string,
    ) -> result<string, string>;
}

world webhook-ai-program {
    import ai;
    export webhook;
}

world webhook-stdout-ai-program {
    import stdout;
    import ai;
    export webhook;
}

world webhook-config-ai-program {
    import config;
    import ai;
    export webhook;
}

world webhook-stdout-config-ai-program {
    import stdout;
    import config;
    import ai;
    export webhook;
}

world webhook-secrets-ai-program {
    import secrets;
    import ai;
    export webhook;
}

world webhook-stdout-secrets-ai-program {
    import stdout;
    import secrets;
    import ai;
    export webhook;
}

world webhook-config-secrets-ai-program {
    import config;
    import secrets;
    import ai;
    export webhook;
}

world webhook-stdout-config-secrets-ai-program {
    import stdout;
    import config;
    import secrets;
    import ai;
    export webhook;
}

world webhook-http-ai-program {
    import http-anonymous;
    import ai;
    export webhook;
}

world webhook-stdout-http-ai-program {
    import stdout;
    import http-anonymous;
    import ai;
    export webhook;
}

world webhook-config-http-ai-program {
    import config;
    import http-anonymous;
    import ai;
    export webhook;
}

world webhook-stdout-config-http-ai-program {
    import stdout;
    import config;
    import http-anonymous;
    import ai;
    export webhook;
}

world webhook-secrets-http-ai-program {
    import secrets;
    import http;
    import ai;
    export webhook;
}

world webhook-stdout-secrets-http-ai-program {
    import stdout;
    import secrets;
    import http;
    import ai;
    export webhook;
}

world webhook-config-secrets-http-ai-program {
    import config;
    import secrets;
    import http;
    import ai;
    export webhook;
}

world webhook-stdout-config-secrets-http-ai-program {
    import stdout;
    import config;
    import secrets;
    import http;
    import ai;
    export webhook;
}

world webhook-logs-program {
    import logging;
    export webhook;
}

world webhook-stdout-logs-program {
    import stdout;
    import logging;
    export webhook;
}

world webhook-config-logs-program {
    import config;
    import logging;
    export webhook;
}

world webhook-stdout-config-logs-program {
    import stdout;
    import config;
    import logging;
    export webhook;
}

world webhook-secrets-logs-program {
    import secrets;
    import logging;
    export webhook;
}

world webhook-stdout-secrets-logs-program {
    import stdout;
    import secrets;
    import logging;
    export webhook;
}

world webhook-config-secrets-logs-program {
    import config;
    import secrets;
    import logging;
    export webhook;
}

world webhook-stdout-config-secrets-logs-program {
    import stdout;
    import config;
    import secrets;
    import logging;
    export webhook;
}

world webhook-http-logs-program {
    import http-anonymous;
    import logging;
    export webhook;
}

world webhook-stdout-http-logs-program {
    import stdout;
    import http-anonymous;
    import logging;
    export webhook;
}

world webhook-config-http-logs-program {
    import config;
    import http-anonymous;
    import logging;
    export webhook;
}

world webhook-stdout-config-http-logs-program {
    import stdout;
    import config;
    import http-anonymous;
    import logging;
    export webhook;
}

world webhook-secrets-http-logs-program {
    import secrets;
    import http;
    import logging;
    export webhook;
}

world webhook-stdout-secrets-http-logs-program {
    import stdout;
    import secrets;
    import http;
    import logging;
    export webhook;
}

world webhook-config-secrets-http-logs-program {
    import config;
    import secrets;
    import http;
    import logging;
    export webhook;
}

world webhook-stdout-config-secrets-http-logs-program {
    import stdout;
    import config;
    import secrets;
    import http;
    import logging;
    export webhook;
}

world webhook-ai-logs-program {
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-ai-logs-program {
    import stdout;
    import ai;
    import logging;
    export webhook;
}

world webhook-config-ai-logs-program {
    import config;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-config-ai-logs-program {
    import stdout;
    import config;
    import ai;
    import logging;
    export webhook;
}

world webhook-secrets-ai-logs-program {
    import secrets;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-secrets-ai-logs-program {
    import stdout;
    import secrets;
    import ai;
    import logging;
    export webhook;
}

world webhook-config-secrets-ai-logs-program {
    import config;
    import secrets;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-config-secrets-ai-logs-program {
    import stdout;
    import config;
    import secrets;
    import ai;
    import logging;
    export webhook;
}

world webhook-http-ai-logs-program {
    import http-anonymous;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-http-ai-logs-program {
    import stdout;
    import http-anonymous;
    import ai;
    import logging;
    export webhook;
}

world webhook-config-http-ai-logs-program {
    import config;
    import http-anonymous;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-config-http-ai-logs-program {
    import stdout;
    import config;
    import http-anonymous;
    import ai;
    import logging;
    export webhook;
}

world webhook-secrets-http-ai-logs-program {
    import secrets;
    import http;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-secrets-http-ai-logs-program {
    import stdout;
    import secrets;
    import http;
    import ai;
    import logging;
    export webhook;
}

world webhook-config-secrets-http-ai-logs-program {
    import config;
    import secrets;
    import http;
    import ai;
    import logging;
    export webhook;
}

world webhook-stdout-config-secrets-http-ai-logs-program {
    import stdout;
    import config;
    import secrets;
    import http;
    import ai;
    import logging;
    export webhook;
}

world webhook-host-program {
    import stdout;
    import config;
    import secrets;
    import http;
    import http-anonymous;
    import ai;
    import logging;
    import state;
    export webhook;
}
