[package]
name = "krit-runtime"
description = "Bounded least-authority WebAssembly component host for Krit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
krit-package.workspace = true
krit-wasm.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmtime.workspace = true

[dev-dependencies]
krit.workspace = true
wasm-encoder.workspace = true
wasm-metadata.workspace = true
wasmparser.workspace = true

[lints]
workspace = true
